language: generic

services:
  - docker

env:
  BUILD_IMAGE_NAME: $PROJECT_NAME:$TRAVIS_JOB_ID-sha-$TRAVIS_PULL_REQUEST_SHA
  POSTGRES_VERSION: '11.3'
  REDIS_VERSION: '5.0.5'

before_install:
  - sudo apt-get update
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce


install:
  - docker run -d --name postgres postgres:$POSTGRES_VERSION
  - docker run -d --name redis redis:$REDIS_VERSION
  - docker build --rm --build-arg ENV=dev -t $BUILD_IMAGE_NAME .

script:
  - docker run --rm --env-file .env.test --link redis:redis
               --link postgres:db $BUILD_IMAGE_NAME /bin/sh -c "mix travis"
