version: '3'
services:
  web:
    build: .
    command: mix phx.server
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - .:/messagach/
      - /messagach/_build/db
  db:
    image: postgres:10.5
    volumes:
      - ./_build/db/data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
