version: '3'
services:
  web:
    build:
      context: .
      args:
        ENV: dev
    command: mix phx.server
    ports:
      - '4000:4000'
    depends_on:
      - db
      - redis
    volumes:
      - .:/messagach/
      - /messagach/_build/db
    env_file:
      - .env.development
  redis:
    image: redis:5.0.5
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - './_build/db/data/redis:/data'
  db:
    image: postgres:11.3
    volumes:
      - ./_build/db/data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
